- ec2_lc:
    name: "{{app_name}}-{{ ansible_date_time.iso8601 | regex_replace('[^a-zA-Z0-9]', '-') }}"
    image_id: "{{lc_ami_image_id}}"
    key_name: "{{lc_key_name}}"
    security_groups: ['{{lc_security_group}}']
    instance_type: "{{lc_instance_type}}"
    region: "{{lc_region}}"
    assign_public_ip: "{{lc_assign_public_ip}}"
  register: lc1
  when: "{{lc_assign_public_ip}} is defined"

- ec2_lc:
    name: "{{app_name}}-{{ ansible_date_time.iso8601 | regex_replace('[^a-zA-Z0-9]', '-') }}"
    image_id: "{{lc_ami_image_id}}"
    key_name: "{{lc_key_name}}"
    security_groups: ['{{lc_security_group}}']
    instance_type: "{{lc_instance_type}}"
    region: "{{lc_region}}"
  register: lc2
  when: "{{lc_assign_public_ip}} is not defined"

- name: combine A and B variables
  set_fact:
    lc: "{{ lc1 if lc_assign_public_ip is defined else lc2 }}"  

- debug:
    msg: "{{lc}}"